name: Auto Update Steam Backup Report

on:
  schedule:
    - cron: "0 * * * *"  # every hour
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download and Install SteamCMD
        run: |
          mkdir -p ~/steamcmd
          cd ~/steamcmd
          wget https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz
          tar -xvzf steamcmd_linux.tar.gz

      - name: Install PowerShell
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https software-properties-common
          wget -q "https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb"
          sudo dpkg -i packages-microsoft-prod.deb
          sudo apt-get update
          sudo apt-get install -y powershell

      - name: Run Steam Backup Checker
        run: |
          pwsh ./Check-SteamBackups.ps1 `
            -SteamCmdPath "/home/runner/steamcmd/steamcmd.sh" `
            -RepoPath "." `
            -GitUserName "FirebrawlX" `
            -GitUserEmail "andree.frank@gmail.com"
        shell: pwsh

      - name: Set up git for GitHub Actions
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

      - name: Commit and push index.html and games.json
        run: |
          git add index.html games.json
          git commit -m "Update Steam backup report $(date '+%Y-%m-%d %H:%M')" || echo "No changes to commit"
          git pull --rebase
          git push
