name: Auto Update Steam Backup Report

on:
  schedule:
    - cron: "0 * * * *"  # every hour
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install SteamCMD
        run: sudo apt-get update && sudo apt-get install -y steamcmd

      - name: Setup PowerShell
        uses: PowerShell/setup-pwsh@v2

      - name: Run Steam Backup Checker
        run: |
          pwsh ./Check-SteamBackups.ps1 `
            -BackupDir "./Games" `
            -SteamCmdPath "/usr/games/steamcmd" `
            -RepoPath "." `
            -GitUserName "FirebrawlX" `
            -GitUserEmail "andree.frank@gmail.com"
        shell: pwsh
